import {
  detailAuthoringReference,
  RELAYER_ICON_FAMILY_GROUPS,
  RELAYER_ICON_NAMES,
  relayerIconFamily,
} from "@relayer/graph-client";

// Icons grouped by the family that colours a node, so agents pick a content icon for a node's subject.
export const NODE_ICON_GUIDANCE = [
  "Valid node icons: choose the content icon that names what the node is about; its family gives the node its colour.",
  ...RELAYER_ICON_FAMILY_GROUPS.map(({ label, icons }) => `- ${label}: ${icons.join(", ")}.`),
  `Signal icons have no colour and are only for status, warning, confirmation, or pointer nodes, never for a node's subject: ${RELAYER_ICON_NAMES.filter((name) => relayerIconFamily(name) === "neutral").join(", ")}.`,
].join("\n");

export const GRAPH_PRESENTATION_GUIDANCE = `Graph presentation guidance:
You choose the flow of each query: direct work, questions, graph structure, publication, and any available delegation. No node count, recursive-call quota, or update schedule is required. The attached presentation preferences describe the user experience; API examples demonstrate mechanics, not a mandatory sequence.
Capability meanings: a node represents a task-relevant concept with its own detail; a layer arranges connected nodes into a view. Navigate actions expose other views, input actions collect user answers, and invoke actions identify new work. Current publishes the view of this completion before it ends; terminal submission establishes its final result.
Available presentation capabilities: authored HTML/CSS can express layout, diagrams, comparisons, and other visual explanations without image files. Graph actions provide navigation and supported controls. The visual-assets API can discover, register, and bind images when needed. Asset inspection resolves metadata and preview files; seeing those files requires the selected harness and model to support native image inspection. Use the language-specific public API recipes below.
- Each layer should explain its scope as a coherent whole. The root layer should let the user understand the overall problem or task, the material work or logic, and the result, evidence, or limitations that matter. A child layer should do the same for the narrower scope it owns.
- Choose "expand" when another layer should deepen one part of the current explanation. Each expansion should add a useful level of detail rather than merely restating its parent.
- Choose "reference" for supporting evidence or reusable context that helps the current explanation but is not part of its decomposition. A layer reached as a reference may author only further reference actions; it must not author expand or invoke actions.
- Choose "invoke" when the useful next step requires a new agent interaction. Do not use invoke as a substitute for explanation that belongs in the current graph.
- Choose "input" when the user should provide a bounded text, single-select, or multi-select value for their next ordinary interaction. Input is optional authored UI, not an invoke, navigation target, required field, or independent task. Use stable option keys and concise prompts; do not add one to every node.
- In this presentation-choice guidance only, choosing "stop" means leaving the node without a further action because expand, reference, and invoke would not materially improve understanding or help the user proceed. It is not GraphComplete's stopped lifecycle state and does not stop the interaction: you must still finish the response with a successful graph.submit call.`;

export const CURRENT_WORKSPACE_GUIDANCE = `You may be working in a graph with other live agents. Treat the graph as a live, user-facing workspace rather than only a final response format. Your current pointer communicates where your work presently stands before completion; consider updating it as the work evolves, when the user would gain a more useful view rather than on every change. Advancing current does not complete the interaction. Final graph submission completes it. The graph is the user's interface: write every node about the user's task, such as findings, decisions, open questions, and progress in the task's own terms. Never expose execution mechanics in graph content, such as layers or layer numbers, revisions, pointers, completions, child agents, or internal identifiers.
Publication contract: construct nodes, layers, and actions with stable client keys. Bind detail controls to the same action objects and exact containing source layer before checkpointing details. Submit nodes, edges, and layers, then register ALL actions for the closure, including the interaction root expand action. Only after those writes may you advance current to the root layer. Do not advance child layers before connecting them. Advancing current accepts the published closure. It is not a draft preview. Accepted node identity, title, semantic text, layer topology, and existing actions remain immutable. Reuse alone grants no action authority. Only an exact frozen attached-node navigation grant permits the exception: stage new navigate actions and any supported full presentation replacement for that attached node, preserving existing controls. Only terminal submission publishes these additions and replacements; Advance never does. Otherwise author new records for changed content while preserving access to prior current. A fresh object with the same key can repair a draft, but cannot edit an accepted record. Advancing is optional; final graph.submit remains required.
Public visual authoring reference (generated from the compiler; no source inspection needed): ${JSON.stringify(detailAuthoringReference())}
${NODE_ICON_GUIDANCE}
Use CSS custom properties and the listed properties/functions; allowed names still have value and selector validation. Inline SVG, canvas, scripts, event handlers, arbitrary data attributes, raw URL attributes, background images, and gradients are unsupported. Use HTML/CSS shapes or registered image assets. Bind asset and control attributes through the public template API, not strings. Runtime control state comes from graph actions, not authored attributes: runtimeOwnedAttributes are prohibited even if also listed for an element. Checkpoint errors identify the component and rejected construct; repair that specific draft before publication.
Theme authoring: design readable light AND dark presentations in the same saved detail. Relayer owns the active theme; select it with [data-relayer-theme="light"] and [data-relayer-theme="dark"] in component CSS. The marker is on a runtime-owned inner scope, inside the protected detail host. For example, [data-relayer-theme="light"] .explanation { color: #182c34; background-color: #fafbf9; } and [data-relayer-theme="dark"] .explanation { color: #edf2f3; background-color: #121619; }. Relayer light uses pale neutral surfaces and dark text; dark uses charcoal surfaces and light text. These palette examples are guidance, not mandatory colors or a layout recipe. You control styling, layout, and visual composition. Cover text, surfaces, borders, chart marks and labels, controls, hover and keyboard focus with suitable contrast. Preserve meaning across modes, including semantic chart colors. Theme switching happens without generation or replacing controls. Keep each input/action on its existing stable capability mount and reposition/restyle it as needed; do not create duplicate inputs for the two themes. For different illustrations or static compositions, bind both variants as ordinary assets/content, give each a class, and use the theme selectors with display rules to show the matching variant. Share an asset across themes when it works in both. The theme marker is host-owned: do not author it into HTML or use operating-system prefers-color-scheme as the product theme. Missing theme-specific styles render the same authored presentation in both modes; they are not rejected or automatically recolored.`;
