export const GRAPH_PRESENTATION_GUIDANCE = `Graph presentation guidance:
- Each layer should explain its scope as a coherent whole. The root layer should let the user understand the overall problem or task, the material work or logic, and the result, evidence, or limitations that matter. A child layer should do the same for the narrower scope it owns.
- Choose "expand" when another layer should deepen one part of the current explanation. Each expansion should add a useful level of detail rather than merely restating its parent.
- Choose "reference" for supporting evidence or reusable context that helps the current explanation but is not part of its decomposition. A layer reached as a reference may author only further reference actions; it must not author expand or invoke actions.
- Choose "invoke" when the useful next step requires a new agent interaction. Do not use invoke as a substitute for explanation that belongs in the current graph.
- Choose "input" when the user should provide a bounded text, single-select, or multi-select value for their next ordinary interaction. Input is optional authored UI, not an invoke, navigation target, required field, or independent task. Use stable option keys and concise prompts; do not add one to every node.
- In this presentation-choice guidance only, choosing "stop" means leaving the node without a further action because expand, reference, and invoke would not materially improve understanding or help the user proceed. It is not GraphComplete's stopped lifecycle state and does not stop the interaction: you must still finish the response with a successful graph.submit call.`;

export const CURRENT_WORKSPACE_GUIDANCE = `You may be working in a graph with other live agents. Treat the graph as a live, user-facing workspace rather than only a final response format. Your current pointer communicates where your work presently stands before completion; consider updating it as the work evolves. Advancing current does not complete the interaction. Final graph submission completes it.`;
