[workspace]
members = [
  "crates/relayer-app-server",
  "crates/relayer-graph-core",
  "crates/relayer-graph-server",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.0.0"

[workspace.dependencies]
anyhow = "1.0"
axum = "0.8"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "sqlite", "migrate", "macros"] }
thiserror = "2.0"
tokio = { version = "1.49", features = ["fs", "macros", "net", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6", features = ["fs"] }
tempfile = "3.23"
uuid = { version = "1.20", features = ["serde", "v4"] }
url = "2.5"
