// PROTOTYPE — throwaway (issue #684). What building the prototype taught us, for the
// PRD write-up (O3). Each finding names what it affects.
export const FINDINGS = [
  ["Byte ranges are required", "The video could not jump to a segment until the artifact server answered HTTP Range requests. The production file handler (a custom protocol in Electron) must support ranges, or video parts (D11) silently start at 0:00.", "P2 · D11"],
  ["An iframe swallows the pointer", "Mouse movement over the artifact never reaches Relayer, so an auto-hiding toolbar cannot reappear by hovering the content. The prototype keeps a 26 px address strip at the top: it satisfies 'address always visible' (D21) and is the hover target. With a WebContentsView the same problem exists — plan for the strip.", "V1 · D13 · D21"],
  ["External links must go through main", "window.open from the viewer is caught by popup blocking because the click happened inside the artifact. In Relayer the reporter message should reach main, which calls shell.openExternal for http/https only.", "V5"],
  ["Seed before first paint", "Seeding storage needs a same-origin bootstrap that clears, seeds, then navigates. In Electron do this on the artifact's partition before loadURL (session storage APIs / cookies.set), not with an injected page.", "P5 · P6 · D23"],
  ["One origin per artifact node is enough isolation for the prototype", "Artifact code could not read Relayer's API (CORS), the parent DOM (SecurityError) or another artifact's storage. Production should still use a separate partition per node with no preload, as the draft-preview capture window already does.", "P7 · D6"],
  ["PDF: render the requested page first", "Rendering all pages before scrolling made 'page 4' feel broken for several seconds. Lay out all pages at size, jump, then render the target page first.", "P1"],
  ["Failed starts must not loop", "A naive 'start if not running' restarted a crashing app on every status poll. Polling reports; only opening the viewer or Retry starts.", "S5 · D37"],
  ["The interaction node has nowhere to put screenshots", "Sent annotations carry location and text into the interaction's contexts, but the real interaction node has no image field (the prototype keeps them in memory). Needs a schema decision.", "N3 · D40"],
  ["Agent-made spreadsheets can show blank totals", "openpyxl writes formulas without cached results, and SheetJS does not calculate, so the Total row renders empty. Either recalculate on view, or tell agents to save calculated values (e.g. a LibreOffice recalc pass) — otherwise the viewer looks broken on exactly the files agents produce.", "T10 · D10"],
  ["Excel charts are dropped", "SheetJS renders values and formulas' cached results but not the workbook chart. Acceptable for v1 per D10b; say so in the viewer.", "T10"],
  ["PowerPoint charts mis-render", "pptx-preview draws text slides well, but the python-pptx column chart shows axes with no bars and a Chinese default title (图表标题, 'Chart title'). Agent-made decks often contain charts, so D10b's 'accept and improve' needs a plan: export a PDF next to decks with charts, or a different renderer.", "T11 · D10b"],
  ["pptx-preview licence", "pptx-preview is closed-source (free to use, source not published). Check the licence before shipping P3.", "T11 · D10"],
  ["The toolbar covers the top of the artifact while shown", "Overlaying keeps the artifact truly full-screen, but while visible the 48 px toolbar hides the site's own navigation for ~2.6 s after opening. Alternative: push content down while the toolbar is open. Worth a look while picking O1.", "V1 · D13"],
  ["The viewer shows no navigate actions", "The artifact node can still carry navigate actions and references (D8), but they appear only in the graph's Node Details. The viewer's top bar is Graph, title, address, Annotate and ⋯ (Open externally). Decided 2026-10-06.", "V2 V3 · D8 D21"],
  ["The node is the right home for artifact details", "Every case was expressible as one node field (`artifact`) plus `renderer: \"artifact\"` on its layer; the server invoke fit as an invoke action with `invoke: \"server\"`. The public snapshot parser already carries both through untouched.", "D30 · D32 · D37"],
];
