// Generates the renderer's design tokens, fonts and share preview image from a design config (design-config-plan.md §2).
// RELAYER_DESIGN selects a config by id (designs/<id>.json) or path; otherwise designs/default names it.
import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { wordmark } from "../../desktop/renderer/src/relayer-mark.js";
import { loadStructure, validateDesign } from "./validate.mjs";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const fontsDirectory = resolve(repositoryRoot, "designs/fonts");
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

export async function resolveDesignPath(selection = process.env.RELAYER_DESIGN) {
  const id = selection || (await readFile(resolve(repositoryRoot, "designs/default"), "utf8")).trim();
  return id.endsWith(".json") ? resolve(process.env.INIT_CWD ?? process.cwd(), id) : resolve(repositoryRoot, "designs", `${id}.json`);
}

// Font roles (ui, display, mono) named by the structure, with their committed files and licence.
export async function loadDesignFonts(structure) {
  return Promise.all(Object.entries(structure.fonts ?? {}).map(async ([role, id]) => {
    const font = JSON.parse(await readFile(resolve(fontsDirectory, id, "font.json"), "utf8"));
    const files = await Promise.all([...font.faces.map((face) => face.file), font.licenseFile].map(async (file) => {
      const bytes = await readFile(resolve(fontsDirectory, id, file));
      const face = font.faces.find((candidate) => candidate.file === file);
      if (face && sha256(bytes) !== face.sha256) throw new Error(`Font ${id}/${file} does not match its recorded sha256.`);
      return { path: `design/fonts/${id}/${file}`, bytes };
    }));
    return { role, id, font, files };
  }));
}

export function designCss(config, source, fonts = []) {
  const block = (mode) => [
    ...Object.entries(config.palette.roles).map(([role, value]) => `--${role}:${value[mode]}`),
    ...Object.entries(config.palette.families).flatMap(([id, family]) => [
      `--family-${id}:${family[mode]}`,
      `--family-${id}-icon:${family[`${mode}Icon`]}`,
    ]),
    `color-scheme:${mode}`,
  ].join(";");
  const faces = fonts.flatMap(({ id, font }) => font.faces.map((face) => `@font-face{font-family:"${font.family}";`
    + `src:url("./fonts/${id}/${face.file}") format("woff2");font-weight:${face.weight};font-style:${face.style};`
    + `font-display:swap;unicode-range:${face.unicodeRange}}`));
  const families = fonts.map(({ role, font }) => `--font-${role}:"${font.family}",${font.fallback}`).join(";");
  return `/* Generated by scripts/design/build.mjs from ${source}. Do not edit. */\n`
    + faces.map((face) => `${face}\n`).join("")
    + (families ? `:root{${families}}\n` : "")
    + `:root{${block("dark")}}\n:root[data-theme="light"]{${block("light")}}\n`;
}

// The share link preview (Open Graph) image in the design's dark roles and node families (PD-14).
export function shareImageSvg(config, fonts = []) {
  // A standalone SVG has no custom properties, so follow var(--role) aliases to their colour.
  const role = (name) => {
    const value = config.palette.roles[name].dark;
    const alias = /^var\(--([a-z0-9-]+)\)$/.exec(value);
    return alias ? role(alias[1]) : value;
  };
  const family = (id) => config.palette.families[id].dark;
  const fontFamily = (name) => {
    const font = fonts.find((candidate) => candidate.role === name)?.font;
    return (font ? `${font.family},${font.fallback}` : "-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif").replaceAll("\"", "'");
  };
  const nodes = [[150, 400, "f6"], [410, 270, "f3"], [670, 410, "f4"], [930, 280, "f5"]];
  const arcs = nodes.slice(1).map(([x, y], index) => {
    const [px, py] = nodes[index];
    return `<path d="M${px + 90} ${py}Q${(px + x) / 2 + 90} ${Math.min(py, y) - 60} ${x + 90} ${y}" fill="none" stroke="${role("edge")}" stroke-width="3"/>`;
  });
  const pills = nodes.map(([x, y, id]) => `<rect x="${x}" y="${y - 28}" width="180" height="56" rx="28" fill="${role("node-fill")}" stroke="${role("node-stroke")}" stroke-width="2"/>`
    + `<circle cx="${x + 28}" cy="${y}" r="18" fill="${family(id)}"/>`
    + `<rect x="${x + 58}" y="${y - 5}" width="96" height="10" rx="5" fill="${role("text-faint")}"/>`);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title description">
  <title id="title">Relayer shared conversation</title>
  <desc id="description">A read-only graph snapshot shared from Relayer.</desc>
  <rect width="1200" height="630" fill="${role("bg")}"/>
  ${arcs.join("\n  ")}
  ${pills.join("\n  ")}
  ${wordmark({ ink: role("text"), x: 120, baseline: 128, capHeight: 44 })}
  <text x="120" y="184" fill="${role("text-muted")}" font-family="${fontFamily("ui")}" font-size="26">Shared conversation</text>
  <text x="120" y="548" fill="${role("accent-text")}" font-family="${fontFamily("mono")}" font-size="18" letter-spacing="3">READ-ONLY SNAPSHOT</text>
</svg>
`;
}

const generatedFiles = ["design/design.css", "design/share-og.svg"];

// The files the build writes, relative to desktop/renderer, for artifacts that must ship them.
export async function designOutputFiles(selection) {
  const config = JSON.parse(await readFile(await resolveDesignPath(selection), "utf8"));
  const fonts = await loadDesignFonts(await loadStructure(config.structure));
  return [...generatedFiles, ...fonts.flatMap((font) => font.files.map((file) => file.path))];
}

export async function buildDesign({ selection, outputDirectory = resolve(repositoryRoot, "desktop/renderer/design") } = {}) {
  const path = await resolveDesignPath(selection);
  const bytes = await readFile(path);
  const config = JSON.parse(bytes);
  const structure = await loadStructure(config.structure);
  const { errors, warnings } = validateDesign(config, structure);
  if (errors.length) throw new Error(`Design ${path} is invalid:\n${errors.map((error) => `  ${error.code}: ${error.message}`).join("\n")}`);
  const fonts = await loadDesignFonts(structure);
  const source = path.slice(repositoryRoot.length);
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(resolve(outputDirectory, "design.css"), designCss(config, source, fonts));
  await writeFile(resolve(outputDirectory, "share-og.svg"), shareImageSvg(config, fonts));
  for (const file of fonts.flatMap((font) => font.files)) {
    const target = resolve(outputDirectory, "..", file.path);
    await mkdir(resolve(target, ".."), { recursive: true });
    await writeFile(target, file.bytes);
  }
  console.log(`design: ${config.name} (${source}, sha256 ${sha256(bytes).slice(0, 12)}, ${warnings.length} floor warnings)`);
  return { path, sha256: sha256(bytes), files: [...generatedFiles, ...fonts.flatMap((font) => font.files.map((file) => file.path))] };
}
