// Generated from docs/graph-query-v1-errors.json. Do not edit.
export const GRAPH_QUERY_ERROR_PHASES = {
  "invalid_request": "envelope",
  "unsupported_query_contract_version": "envelope",
  "query_bytes_exceeded": "envelope",
  "query_syntax_invalid": "parse",
  "query_construct_forbidden": "parse",
  "query_construct_unsupported": "parse",
  "unknown_label": "plan",
  "unknown_relationship_type": "plan",
  "unknown_property": "plan",
  "dynamic_schema_forbidden": "plan",
  "query_type_mismatch": "plan",
  "duplicate_output_column": "plan",
  "invalid_aggregate": "plan",
  "ast_depth_exceeded": "plan",
  "variable_limit_exceeded": "plan",
  "pattern_part_limit_exceeded": "plan",
  "traversal_limit_exceeded": "plan",
  "row_limit_exceeded": "plan",
  "inaccessible_or_missing": "authorize",
  "scope_not_granted": "authorize",
  "foreign_draft": "authorize",
  "query_cancelled": "execute",
  "wall_time_exceeded": "execute",
  "examined_expansions_exceeded": "execute",
  "intermediate_rows_exceeded": "execute",
  "invalid_engine_value": "normalize",
  "heterogeneous_list": "normalize",
  "integer_overflow": "normalize",
  "duplicate_record_field": "normalize",
  "result_row_too_large": "encode",
} as const;

export type GeneratedGraphQueryCode = keyof typeof GRAPH_QUERY_ERROR_PHASES;
export type GeneratedGraphQueryPhase = typeof GRAPH_QUERY_ERROR_PHASES[GeneratedGraphQueryCode];
